export const locations = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Ohio",
    "Texas",
    "Florida",
    "Washington",
    "Oregon",
    "Colorado",
    "Arizona",
    "Nevada",
    "Utah",
    "Idaho",
    "Montana",
    "Wyoming",
    "New Mexico",
    "North Dakota",
    "South Dakota",
    "Nebraska",
    "Kansas",
    "Oklahoma",
    "Minnesota",
    "Iowa",
    "Missouri",
    "Arkansas",
    "Louisiana",
    "Mississippi",
    "Alabama",
    "Georgia",
    "Tennessee",
    "Kentucky",
    "Indiana",
    "Michigan",
    "Wisconsin",
    "Illinois",
    "Pennsylvania",
    "West Virginia",
    "Virginia",
    "North Carolina",
    "South Carolina",
    "Maryland",
    "Delaware",
    "New Jersey",
    "Connecticut",
    "Rhode Island",
    "Massachusetts",
    "Vermont",
    "New Hampshire",
    "Maine",
    "Alaska",
    "Hawaii",
];